### ISSUE TITLE
Visual Studio 2019

### ISSUE THREAD

**Issue by DJHightower** [pavel-agarkov/vs-ngx-item-templates#1]
Please update this fine extension to Visual Studio 2019.

**Comment by pavel-agarkov** [comment]
I don't use VS for Angular development any more and I don't use this extension as well.
If you know how to update it - you can create a PR and I will accept and publish a new version.
PS: you will be mentioned in the description.

**Comment by pavel-agarkov** [comment]
I've just published a new version. Please give it a try.

**Comment by davidda** [comment]
@pavel-agarkov The new version seems incompatible with VS 2017 now. I get this error wenn updating from 1.6.1 to 1.7

![image](https://user-images.githubusercontent.com/4145824/56863372-d4b2de80-69b5-11e9-8045-74cbd9885299.png)

**Comment by DJHightower** [comment]
Works in VS2019.

**Comment by pavel-agarkov** [comment]
Looks like when prerequisites are edited through the UI - incorrect versions range is forced.
I've manually entered values proposed by @JasonBro and published a new version again.
Please update to 1.7.1 and let me know.
Thank you.

**Comment by davidda** [comment]
Thank you, it installs fine now in VS 2017.
